export const nboMockRes = {
  mVivaNextBestOffers: {
    offers: [
      {
        campaignName: "NBO.HS.30.145207_APPLE_IPXS_256_Hot_Deal_New_6M ",
        campaignId: 9684,
        offer: "NBO.HS.30.145207_APPLE_IPXS_256_Hot_Deal_New_6M ",
        priority: 106139999,
        validity: 15,
        id: "517798311.517798311.517798311.1667533440000.9684.8121@1049@18225",
        campaignStartDate: "20221104104400",
        campaignEndDate: "20221118235959",
        product_category: "best_hs",
        nbo_field_details: [
          {
            offer_parameter_name:
              "recom_promo_handset_best1_advisory_note2_NBO_handset",
            offer_parameter_value: "req-minpack-699",
          },
          {
            offer_parameter_name:
              "recom_promo_handset_best1_hs_regular_price_NBO_handset",
            offer_parameter_value: "24500.0",
          },
          {
            offer_parameter_name: "recom_promo_handset_best1_hs_hs_campaign",
            offer_parameter_value: "Best Buy 3M (No Contract)",
          },
          {
            offer_parameter_name: "recom_promo_handset_best1_hs_hs_brand",
            offer_parameter_value: "XIAOMI",
          },
          {
            offer_parameter_name:
              "recom_promo_handset_best1_advisory_note1_NBO_handset",
            offer_parameter_value: "offer-upsell",
          },
          {
            offer_parameter_name:
              "recom_promo_handset_best1_promo_offering_cd_NBO_handset",
            offer_parameter_value: "P190926496",
          },
          {
            offer_parameter_name: "recom_promo_handset_best1_hs_model",
            offer_parameter_value: "RM105GX_4/64",
          },
          {
            offer_parameter_name:
              "recom_promo_handset_best1_hs_trade_disc_id_NBO_handset",
            offer_parameter_value: "145171",
          },
        ],
        additional_details: {
          "message type": "Best HS",
          "product name": "NBO.HS.30.145207_APPLE_IPXS_256_Hot_Deal_New_6M ",
          "product code": "145171",
          product_code_2: "",
          product_code_3: "",
          product_code_4: "",
          Product_class: "",
          "USSD No": "",
          common_1: "",
          common_2: "",
          common_3: "",
          common_4: "",
          common_5: "",
          common_6: "",
          common_7: "",
          common_8: "",
          common_9: "",
          common_10: "",
          common_11: "",
          common_12: "",
          common_13: "",
          common_14: "",
          common_15: "",
          common_16: "",
          common_17: "",
          common_18: "",
          common_19: "",
          common_20: "",
          common_21: "",
          common_22: "",
          common_23: "",
          common_24: "",
          common_25: "",
          common_26: "",
          common_27: "",
          common_28: "",
          common_29: "",
          common_30: "",
        },
        channels: {
          "Easy App": {
            esy_reserve04: "esy_reserve04",
            romID: "",
            esy_reserve05: "",
            esy_reserve06: "",
            esy_reserve07: "",
            esy_reserve01: "",
            esy_reserve02: "",
            esy_reserve03: "",
            channelType: "Pull",
          },
          IM: {
            im_reserve02: "",
            im_reserve01: "im_reserve01",
            im_reserve04: "",
            im_reserve03: "",
            im_reserve06: "",
            im_reserve05: "",
            im_reserve07: "",
            channelType: "Pull",
          },
          "My Channel": {
            mc_reserve06: "",
            mc_reserve05: "",
            mc_reserve07: "",
            KeySellingEng: "Change your device ",
            KeySellingThai: "??????????????",
            mc_reserve02: "",
            mc_reserve01: "",
            mc_reserve04: "",
            mc_reserve03: "",
            channelType: "Pull",
          },
          myAIS: {
            reserve9: "",
            reserve8: "",
            offerDescriptionThai: "",
            reserve5: "",
            reserve4: "",
            reserve7: "myais-feature-deal-badge-best-offer",
            reserve6: "6",
            bannerURL: "",
            reserve1: "",
            reserve10: "",
            reserve3: "",
            reserve2: "",
            offerType: "",
            offerMessageThai: "AISqueueReserve1",
            calField1: "",
            calField2: "",
            calField3: "",
            UssdCode: "",
            offerDescriptionEng: "",
            offerMessageEng: "",
            targetURL: "https://m.ais.co.th/PYHb71qto ",
            channelType: "Pull",
          },
          Chatbot: {
            chatb_reserve02: "",
            chatb_reserve01: "chatb_reserve01",
            chatb_reserve04: "",
            chatb_reserve03: "",
            chatb_reserve06: "",
            chatb_reserve05: "",
            chatb_reserve07: "",
            channelType: "Pull",
          },
          "IVR 1175": {
            ivr_reserve06: "",
            ivr_reserve07: "",
            ivr_reserve02: "",
            ivr_reserve03: "",
            ivr_reserve04: "",
            ivr_reserve05: "",
            ivr_reserve01: "ivr_reserve01",
            channelType: "Pull",
          },
          NCP: {
            ncp_reserve01: "ncp_reserve01",
            ncp_reserve02: "",
            ncp_reserve03: "",
            ncp_reserve04: "",
            ncp_reserve05: "",
            ncp_reserve06: "",
            ncp_reserve07: "",
            ncp_reserve08: "",
            ncp_reserve09: "",
            ncp_reserve10: "",
            channelType: "Pull",
          },
        },
      },
      {
        campaignName: "NBO.HS.30.145207_APPLE_IPXS_256_Hot_Deal_New_6M ",
        campaignId: 9683,
        offer: "NBO.HS.30.145207_APPLE_IPXS_256_Hot_Deal_New_6M ",
        priority: 106138999,
        validity: 15,
        id: "517798311.517798311.517798311.1667533440000.9683.8120@1049@18224",
        campaignStartDate: "20221104104400",
        campaignEndDate: "20221118235959",
        product_category: "best_hs",
        nbo_field_details: [
          {
            offer_parameter_name:
              "recom_promo_handset_best2_advisory_note2_NBO_handset",
            offer_parameter_value: "req-minpack-699",
          },
          {
            offer_parameter_name:
              "recom_promo_handset_best2_hs_regular_price_NBO_handset",
            offer_parameter_value: "24500.0",
          },
          {
            offer_parameter_name:
              "recom_promo_handset_best2_advisory_note1_NBO_handset",
            offer_parameter_value: "offer-upsell",
          },
          {
            offer_parameter_name:
              "recom_promo_handset_best2_promo_offering_cd_NBO_handset",
            offer_parameter_value: "P17068673",
          },
          {
            offer_parameter_name:
              "recom_promo_handset_best2_hs_trade_disc_id_NBO_handset",
            offer_parameter_value: "145162",
          },
          {
            offer_parameter_name: "recom_promo_handset_best2_hs_hs_brand",
            offer_parameter_value: "APPLE",
          },
          {
            offer_parameter_name: "recom_promo_handset_best2_hs_model",
            offer_parameter_value: "",
          },
          {
            offer_parameter_name: "recom_promo_handset_best2_hs_hs_campaign",
            offer_parameter_value: "Best Buy 12M Contract 12",
          },
        ],
        additional_details: {
          "message type": "Best HS",
          "product name": "NBO.HS.30.145207_APPLE_IPXS_256_Hot_Deal_New_6M ",
          "product code": "145162",
          product_code_2: "",
          product_code_3: "",
          product_code_4: "",
          Product_class: "",
          "USSD No": "",
          common_1: "",
          common_2: "",
          common_3: "",
          common_4: "",
          common_5: "",
          common_6: "",
          common_7: "",
          common_8: "",
          common_9: "",
          common_10: "",
          common_11: "",
          common_12: "",
          common_13: "",
          common_14: "",
          common_15: "",
          common_16: "",
          common_17: "",
          common_18: "",
          common_19: "",
          common_20: "",
          common_21: "",
          common_22: "",
          common_23: "",
          common_24: "",
          common_25: "",
          common_26: "",
          common_27: "",
          common_28: "",
          common_29: "",
          common_30: "",
        },
        channels: {
          "Easy App": {
            esy_reserve04: "esy_reserve04",
            romID: "",
            esy_reserve05: "",
            esy_reserve06: "",
            esy_reserve07: "",
            esy_reserve01: "",
            esy_reserve02: "",
            esy_reserve03: "",
            channelType: "Pull",
          },
          IM: {
            im_reserve02: "",
            im_reserve01: "im_reserve01",
            im_reserve04: "",
            im_reserve03: "",
            im_reserve06: "",
            im_reserve05: "",
            im_reserve07: "",
            channelType: "Pull",
          },
          "My Channel": {
            mc_reserve06: "",
            mc_reserve05: "",
            mc_reserve07: "",
            KeySellingEng: "Change your device ",
            KeySellingThai: "??????????????",
            mc_reserve02: "",
            mc_reserve01: "",
            mc_reserve04: "",
            mc_reserve03: "",
            channelType: "Pull",
          },
          myAIS: {
            reserve9: "",
            reserve8: "",
            offerDescriptionThai: "",
            reserve5: "",
            reserve4: "",
            reserve7: "myais-feature-deal-badge-hot",
            reserve6: "6",
            bannerURL: "",
            reserve1: "",
            reserve10: "",
            reserve3: "",
            reserve2: "",
            offerType: "",
            offerMessageThai: "AISqueueReserve1",
            calField1: "",
            calField2: "",
            calField3: "",
            UssdCode: "",
            offerDescriptionEng: "",
            offerMessageEng: "",
            targetURL: "https://m.ais.co.th/zGHRWQbIZ ",
            channelType: "Pull",
          },
          Chatbot: {
            chatb_reserve02: "",
            chatb_reserve01: "chatb_reserve01",
            chatb_reserve04: "",
            chatb_reserve03: "",
            chatb_reserve06: "",
            chatb_reserve05: "",
            chatb_reserve07: "",
            channelType: "Pull",
          },
          "IVR 1175": {
            ivr_reserve06: "",
            ivr_reserve07: "",
            ivr_reserve02: "",
            ivr_reserve03: "",
            ivr_reserve04: "",
            ivr_reserve05: "",
            ivr_reserve01: "ivr_reserve01",
            channelType: "Pull",
          },
          NCP: {
            ncp_reserve01: "ncp_reserve01",
            ncp_reserve02: "",
            ncp_reserve03: "",
            ncp_reserve04: "",
            ncp_reserve05: "",
            ncp_reserve06: "",
            ncp_reserve07: "",
            ncp_reserve08: "",
            ncp_reserve09: "",
            ncp_reserve10: "",
            channelType: "Pull",
          },
        },
      },
      {
        campaignName: "NBO.HS.30.145207_APPLE_IPXS_256_Hot_Deal_New_6M ",
        campaignId: 9686,
        offer: "NBO.HS.30.145207_APPLE_IPXS_256_Hot_Deal_New_6M ",
        priority: 106137999,
        validity: 15,
        id: "517798311.517798311.517798311.1667533440000.9686.8123@1049@18223",
        campaignStartDate: "20221104104400",
        campaignEndDate: "20221118235959",
        product_category: "best_hs",
        nbo_field_details: [
          {
            offer_parameter_name: "recom_promo_handset_best3_hs_hs_campaign",
            offer_parameter_value: "Hot Deal EX",
          },
          {
            offer_parameter_name: "recom_promo_handset_best3_hs_hs_brand",
            offer_parameter_value: "OPPO",
          },
          {
            offer_parameter_name: "recom_promo_handset_best3_hs_model",
            offer_parameter_value: "A775G_6/128",
          },
          {
            offer_parameter_name:
              "recom_promo_handset_best3_advisory_note2_NBO_handset",
            offer_parameter_value: "mandatory-hotdeal",
          },
          {
            offer_parameter_name:
              "recom_promo_handset_best3_hs_regular_price_NBO_handset",
            offer_parameter_value: "24500.0",
          },
          {
            offer_parameter_name:
              "recom_promo_handset_best3_advisory_note1_NBO_handset",
            offer_parameter_value: "offer-upsell",
          },
          {
            offer_parameter_name:
              "recom_promo_handset_best3_promo_offering_cd_NBO_handset",
            offer_parameter_value: "P18094885",
          },
          {
            offer_parameter_name:
              "recom_promo_handset_best3_hs_trade_disc_id_NBO_handset",
            offer_parameter_value: "",
          },
        ],
        additional_details: {
          "message type": "Best HS",
          "product name": "NBO.HS.30.145207_APPLE_IPXS_256_Hot_Deal_New_6M ",
          "product code": "145224",
          product_code_2: "",
          product_code_3: "",
          product_code_4: "",
          Product_class: "",
          "USSD No": "",
          common_1: "",
          common_2: "",
          common_3: "",
          common_4: "",
          common_5: "",
          common_6: "",
          common_7: "",
          common_8: "",
          common_9: "",
          common_10: "",
          common_11: "",
          common_12: "",
          common_13: "",
          common_14: "",
          common_15: "",
          common_16: "",
          common_17: "",
          common_18: "",
          common_19: "",
          common_20: "",
          common_21: "",
          common_22: "",
          common_23: "",
          common_24: "",
          common_25: "",
          common_26: "",
          common_27: "",
          common_28: "",
          common_29: "",
          common_30: "",
        },
        channels: {
          "Easy App": {
            esy_reserve04: "esy_reserve04",
            romID: "",
            esy_reserve05: "",
            esy_reserve06: "",
            esy_reserve07: "",
            esy_reserve01: "",
            esy_reserve02: "",
            esy_reserve03: "",
            channelType: "Pull",
          },
          IM: {
            im_reserve02: "",
            im_reserve01: "im_reserve01",
            im_reserve04: "",
            im_reserve03: "",
            im_reserve06: "",
            im_reserve05: "",
            im_reserve07: "",
            channelType: "Pull",
          },
          "My Channel": {
            mc_reserve06: "",
            mc_reserve05: "",
            mc_reserve07: "",
            KeySellingEng: "Change your device ",
            KeySellingThai: "??????????????",
            mc_reserve02: "",
            mc_reserve01: "",
            mc_reserve04: "",
            mc_reserve03: "",
            channelType: "Pull",
          },
          myAIS: {
            reserve9: "",
            reserve8: "",
            offerDescriptionThai: "",
            reserve5: "",
            reserve4: "",
            reserve7: "myais-feature-deal-badge-recommended",
            reserve6: "6",
            bannerURL: "",
            reserve1: "",
            reserve10: "",
            reserve3: "",
            reserve2: "",
            offerType: "",
            offerMessageThai: "AISqueueReserve1",
            calField1: "",
            calField2: "",
            calField3: "",
            UssdCode: "",
            offerDescriptionEng: "",
            offerMessageEng: "",
            targetURL:
              "https://www.ais.th/promotion/hotdeal-smartphone-5g/xiaomi-redmi-10-5g-4-64gb/ ",
            channelType: "Pull",
          },
          Chatbot: {
            chatb_reserve02: "",
            chatb_reserve01: "chatb_reserve01",
            chatb_reserve04: "",
            chatb_reserve03: "",
            chatb_reserve06: "",
            chatb_reserve05: "",
            chatb_reserve07: "",
            channelType: "Pull",
          },
          "IVR 1175": {
            ivr_reserve06: "",
            ivr_reserve07: "",
            ivr_reserve02: "",
            ivr_reserve03: "",
            ivr_reserve04: "",
            ivr_reserve05: "",
            ivr_reserve01: "ivr_reserve01",
            channelType: "Pull",
          },
          NCP: {
            ncp_reserve01: "ncp_reserve01",
            ncp_reserve02: "",
            ncp_reserve03: "",
            ncp_reserve04: "",
            ncp_reserve05: "",
            ncp_reserve06: "",
            ncp_reserve07: "",
            ncp_reserve08: "",
            ncp_reserve09: "",
            ncp_reserve10: "",
            channelType: "Pull",
          },
        },
      },
    ],
    profiles: {
      data: {
        "recom_addon_best1_reason_to_advise-NBO_Package":
          "ส่วนเกินค่าโทรและเน็ตลดสปีด",
        "arpu_min_promo-NBO_Package": "500.0",
        "seg_over_packprice-NBO_Package": "over-packprice",
        "seg_ppu_user_type-NBO_Package": "09_other",
        "recom_promo_best1_reason_to_advise-NBO_Package":
          "ส่วนเกินค่าโทรและเน็ตลดสปีด",
        "seg_risky_user-NBO_Package": "non-risky",
      },
    },
  },
};
