name: UAT - CI

on:
  push:
    tags:
      - '*'
  workflow_dispatch:   
env:
  CI: false
  ENV_TAG: 'preprod'
jobs:
  build:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v3
      - name: Replace Image Tag  
        uses: cschleiden/replace-tokens@v1
        with:
              files: '["**/*.json"]'
        env:
              ENV: ${{ env.ENV_TAG}}
      - name: Set env
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: npm Install
        run: npm install --force

      - name: npm Build
        run: npm run build --if-present
      - name: Packing Arifact Files
        run: |
          cd ${{ github.workspace }}/
          tar -zcvf artifact-fed-node-uat-${{ env.RELEASE_VERSION }}.tar.gz *
      - name: Upload Artifact Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ github.workspace }}/artifact-fed-node-uat-${{ env.RELEASE_VERSION }}.tar.gz
